### ISSUE TITLE
Purpose of separate datasets

### ISSUE THREAD

**Issue by EXJUSTICE** [ak9250/stylegan-art#1]
Great work on the use of styleGAN's to generate portraits guys!

Quick question on the collation of such a large dataset  - your only purpose was to increase the training dataset size, correct? Is there some recommended dataset size for effective StyleGAN?

In addition, I've worked with autoencoders and style transfer code before - styleGAN's do not by definition allow for the application of art styles to real photos, correct? All data must be consistent in style for maximum believability

EDIT: Ipynb directories are incorrect. Also, dnnlib cannot be found during training

**Comment by ak9250** [comment]
A bigger dataset in general will help especially if you are not transfer learning. The ffhq dataset is 70k in size but for transfer learning a smaller dataset 1k-5k can be used. You can do style transfer but not something I have tried. 
Do you which cell is incorrect and what you ran while getting that error?

**Comment by EXJUSTICE** [comment]
Thanks for the explanation and the reply

I'd draw attention to a couple of cells, if you have time please give the notebook another run, maybe on a fresh runtime

"!mv /content/portrait.zip /content/stylegan/portraitbig/"
- Cant find the portrait.zip , maybe needs to be specified during download call?

"!python dataset_tool.py create_from_images datasets/smalls/ /content/stylegan/portraitbig/"
- Dataset tool not found. I think for some reason we cant access the cloned repository? 
"cd training/"
- You never called mkdir for this directory, maybe an oversight? This is needed for the trainloop files

Also, getting a dnnlib not found at the end, also a problem perhaps with accessing the cloned repo?

**Comment by ak9250** [comment]
Hi I just ran the first part for moving the zip file into portrait big and it works
![Screen Shot 2019-03-14 at 11 00 39 AM](https://user-images.githubusercontent.com/6818285/54367273-808fad00-4648-11e9-94bd-3ac76a8aef2e.png)
looking into the second part

**Comment by EXJUSTICE** [comment]
Are you running it locally or on colab btw? I was running on colab

Sent from my Huawei Mobile

-------- Original Message --------
Subject: Re: [ak9250/stylegan-art] Purpose of separate datasets (#1)
From: ak9250
To: ak9250/stylegan-art
CC: "Xu, Yijie" ,Author


Hi I just ran the first part for moving the zip file into portrait big and it works
[Screen Shot 2019-03-14 at 11 00 39 AM]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6818285%2F54367273-808fad00-4648-11e9-94bd-3ac76a8aef2e.png&data=02%7C01%7CYIJIE.XU.10%40UCL.AC.UK%7Cedec592474d54aba35f408d6a88e093a%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C636881725326054353&sdata=Xw63kruw5OzOHS1tAC7Z19Xq79lRYSwWJfJoyuxAzIk%3D&reserved=0>
looking into the second part

**Comment by ak9250** [comment]
yes this is on colab, see screenshot, did you do save a copy to drive?

**Comment by EXJUSTICE** [comment]
No I simply downloaded the notebook and uploaded it from my local directory, it needs to be on my gdrive ?

-------- Original Message --------
Subject: Re: [ak9250/stylegan-art] Purpose of separate datasets (#1)
From: ak9250
To: ak9250/stylegan-art
CC: "Xu, Yijie" ,Author


yes this is on colab, see screenshot, did you do save a copy to drive?

**Comment by ak9250** [comment]
yes click on save a copy to drive, you dont need to download it, to run in colab, it runs on google cloud servers for free gpu
![Screen Shot 2019-03-14 at 11 08 48 AM](https://user-images.githubusercontent.com/6818285/54367946-a2d5fa80-4649-11e9-83ab-ca8f67c368b1.png)

**Comment by EXJUSTICE** [comment]
I'll give it a try thanks

I assume the rest of the cells ran without problems?

-------- Original Message --------
Subject: Re: [ak9250/stylegan-art] Purpose of separate datasets (#1)
From: ak9250
To: ak9250/stylegan-art
CC: "Xu, Yijie" ,Author


yes click on save a copy to drive, you dont need to download it, to run in colab, it runs on google cloud servers for free gpu
[Screen Shot 2019-03-14 at 11 08 48 AM]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6818285%2F54367946-a2d5fa80-4649-11e9-83ab-ca8f67c368b1.png&data=02%7C01%7CYIJIE.XU.10%40UCL.AC.UK%7C3dc7632cadea4eeccc0908d6a88f1043%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C636881729739283264&sdata=DcmcSQch%2Ba1ISyi51ZXrkotuiJwy6lM7%2BS3fts5BtQY%3D&reserved=0>

**Comment by ak9250** [comment]
yes so far I am at the cropping part, everything runs fine but takes a bit as there are alot of images

**Comment by EXJUSTICE** [comment]
Great mate I'll put it to run here and report back!

-------- Original Message --------
Subject: Re: [ak9250/stylegan-art] Purpose of separate datasets (#1)
From: ak9250
To: ak9250/stylegan-art
CC: "Xu, Yijie" ,Author


yes so far I am at the cropping part, everything runs fine but takes a bit as there are alot of images

**Comment by ak9250** [comment]
one thing, if you are not scraping images skip those cells as it is for gathering a new dataset. I will close this issue for now, let me know if it works.

**Comment by EXJUSTICE** [comment]
Thanks very much!

Sent from my Huawei Mobile

-------- Original Message --------
Subject: Re: [ak9250/stylegan-art] Purpose of separate datasets (#1)
From: ak9250
To: ak9250/stylegan-art
CC: "Xu, Yijie" ,Author


one thing, if you are not scraping images skip those cells as it is for gathering a new dataset. I will close this issue for now, let me know if it works.

**Comment by ak9250** [comment]
ok I actually noticed a problem with generating tfrecords was pointing to portraits big but it should be pointing to Faces dir after using autocrop so I commited a fix for that. Thanks

**Comment by EXJUSTICE** [comment]
Glad to be of service. Let it run to the training stage and keep me in the loop! High chance I just screwed up.Will run it again tomorrow :)



-------- Original Message --------
Subject: Re: [ak9250/stylegan-art] Purpose of separate datasets (#1)
From: ak9250
To: ak9250/stylegan-art
CC: "Xu, Yijie" ,Author


ok I actually noticed a problem with generating tfrecords was pointing to portraits big but it should be pointing to Faces dir after using autocrop so I commited a fix for that. Thanks

**Comment by ak9250** [comment]
I ran it to training after that so everything should work now.

**Comment by EXJUSTICE** [comment]
Works for me now! I've limited experience with colab however - does the ipynb produce an output model for storage? Where does it store it to? Do I need to write another line to extract the model?

**Comment by ak9250** [comment]
yes the output if it is transfer learning will show in about 6 hours and it is under the files structures, results/000-cant rember/network-snapshot.pkl that is the trained model. Just click on it twice and it will download the model to your computer or you can mount google drive and copy it to google drive. Colab runs for 12 hours of free gpu so you have to save you model before the 12 hour mark as colab will reset.
