### ISSUE TITLE
The Kaggle kernel wont succeed

### ISSUE THREAD

**Issue by ajthinking** [ak9250/stylegan-art#2]
Thank you for posting this. I get errors on kaggle (not sure if I do something wrong)

![image](https://user-images.githubusercontent.com/3457668/56073102-a805a100-5dd1-11e9-80dd-9380a0fb6552.png)

Yesterday there was another error "to many subdirs" or similar. Between my attempts I deleted/reforked the kernel. Any ideas?

**Comment by ak9250** [comment]
hi yes kaggle has a problem when committing a notebook with too many files are you trying to get the outputs?
What I did was save the outputs to dropbox by uploading them
do pip install dropbox
then use the dropbox api to upload files, I can post the code for that soon

**Comment by ajthinking** [comment]
Got it, thanks! I just tried commiting without any changes.  Would love to see that dropbox code or something to make it run out of the box.

Den 13 apr. 2019 10:34 skrev ak9250 <notifications@github.com>:

hi yes kaggle has a problem when committing a notebook with too many files are you trying to get the outputs?
What I did was save the outputs to dropbox by uploading them
do pip install dropbox
then use the dropbox api to upload files, I can post the code for that soon

**Comment by ak9250** [comment]
here is the dropbox upload code

import dropbox
import dropbox.files


CHUNK_SIZE = 4 * 1024 * 1024


def upload_stream(dbx, readable, dest_path):
    d = readable.read(CHUNK_SIZE)
    offset = len(d)

    session = dbx.files_upload_session_start(d)
    cursor = dropbox.files.UploadSessionCursor(session_id=session.session_id,
                                               offset=offset)
    while True:
        d = readable.read(CHUNK_SIZE)
        offset += len(d)

        if len(d) == 0:
            commit = dropbox.files.CommitInfo(path=dest_path)
            return dbx.files_upload_session_finish(d, cursor, commit)
        dbx.files_upload_session_append_v2(d, cursor)
        cursor.offset = offset


def upload_file(dbx, file_path, dest_path):
    with open(file_path, 'rb') as f:
        return upload_stream(dbx, f, dest_path)


if __name__ == '__main__':
    APP_TOKEN = 'your app token here'
    dbx = dropbox.Dropbox(APP_TOKEN)
    print(upload_file(dbx, '/kaggle/working/stylegan/results/00000-sgan-custom-1gpu/network-snapshot.pkl', '/foldername/network-snapshot.pkl'))

**Comment by ajthinking** [comment]
Thank you!
