### ISSUE TITLE
Project dependencies/Quickstart

### ISSUE THREAD

**Issue by aspin** [ak9250/stylegan-art#4]
I might be daft and just unfamiliar with this Jupyter notebooks, but is there a requirements file of all the dependencies needed to run this project? I forked and cloned the repo, but I get dependency issues all over the place and am just resolving them by hand in the virtualenv I've generated.

**Comment by ak9250** [comment]
have you tried running the colab notebook top to bottom, you should not have problems with dependencies in there

**Comment by aspin** [comment]
I have some decent local hardware that I wanted to run the notebook locally to not need to save/resume check points. The colab does work fine for me though.

**Comment by ak9250** [comment]
ok closing as it works in colab
