### ISSUE TITLE
Saving/Resuming checkpoints

### ISSUE THREAD

**Issue by mbodge** [ak9250/stylegan-art#5]
Hi there, thanks for posting this code...I'm new to ML and StyleGAN has been a big chunk to bite off.  Your code really helps

Question: in the Colab file you said the following:

`Note: colab will reset after 12 hours make sure to save your model checkpoints to google drive around 6 hours mark (one tick), the second tick will show up before the reset but I have lost work by not being able to save it to drive in time, then go to runtime->reset all runtimes. Now copy your train model back into colab and start training again from the previous checkpoint.
`

Can you provide guidance on how to do this? I see people doing this for other types of models but I'm not sure how to go about saving this (is it the .pkl file?) and how do I reset the runtime and go back in and load it back to keep training?

Any help would be amazing, thanks!

**Comment by ak9250** [comment]
Hi, two ways, one is you go the the file tab in colab and double click right click on the pkl file to download it and you set the model to load in training_loop.py which is shown in the notebook

**Comment by mbodge** [comment]
Thanks for the quick response...do i need to go through all of the steps in
the notebook again (ie: searching for photos for the dataset etc)?
